networks:
  voiceline-net:

volumes:
  voiceline-db:

services:
  voiceline-db:
    build:
      context: ./deploy
      dockerfile: db.Dockerfile
    container_name: voiceline-db
    user: root  # needed because windows hates me
    volumes:
      - voiceline-db:/var/lib/postgresql/data
    networks:
      - voiceline-net
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  voiceline-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: voiceline-keycloak
    depends_on:
      - voiceline-db
    networks:
      - voiceline-net
    ports:
      - "8403:8080"  # expose to host port 8403
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: voiceline-db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_DATABASE: keycloak
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: admin  # Указываем временное имя администратора
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin  # Указываем временный пароль администратора
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      PROXY_ADDRESS_FORWARDING: 'true'
    command:
      - start-dev  # for new version of keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway"

  voiceline-users:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voiceline-users
    networks:
      - voiceline-net
    ports:
      - "8087:8087"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - voiceline-db
    environment:
      - VOICELINE_CONFIG_PATH=config/prod.yaml
