env: "local"
version: "1.0.0"
db_connect: "host=localhost port=25432 dbname=keycloak user=keycloak password=password client_encoding=UTF8 sslmode=disable"
port: 8087
use_tracing: true
tracing_address: "http://localhost:14268/api/traces"

keycloak:
  server: http://localhost:8403/
  realm: master
  client_secret: A1GpPrwmld784l9dpMNI7oEMZzdkivMh
  client_id: myapp